---
controller_credentials:
  - name: cred_mach_root
    credential_type: Machine
    organization: "{{ ansible_organization_name }}"
    description: root local password
    inputs:
      username: root
      password: "{{ root_machine_pass }}"
  - name: cred_sat6_admin
    credential_type: Red Hat Satellite 6
    description: Red Hat Satellite admin credential
    organization: "{{ ansible_organization_name }}"
    inputs:
      username: admin
      password: "{{ satellite_password }}"
      host: https://satellite.london.example.com
# here is an example for getting git ssh cred working
# - name: github
#   credential_type: Source Control
#   organization: config_as_code
#   description: github
#   inputs:
#     username: ""
#     ssh_key_data: "{{ ssh_priv_key }}"
#     ssh_key_unlock: "{{ ssh_key_unlock }}"
...
