controller_workflows:
  - name: wflow_ipu_rhel7
    description: In-place upgrade from RHEL 7 to RHEL 8
    extra_vars: ''
    survey_enabled: true
    allow_simultaneous: false
    ask_variables_on_launch: false
    inventory: inv_satellite_production
    limit: inv_satellite_production
    scm_branch:
    ask_inventory_on_launch: true
    ask_scm_branch_on_launch: false
    ask_limit_on_launch: true
    webhook_service: ''
    webhook_credential:
    organization: Default
    schedules: []
    simplified_workflow_nodes:
      - all_parents_must_converge: false
        identifier: tpl_leapp_remediate
        unified_job_template: tpl_leapp_remediate
        credentials: []
        success_nodes:
          - tpl_leapp_bigboot
        failure_nodes: []
        always_nodes: []
      - all_parents_must_converge: false
        identifier: tpl_leapp_bigboot
        unified_job_template: tpl_leapp_bigboot
        credentials: []
        success_nodes:
          - tpl_leapp_analysis
        failure_nodes: []
        always_nodes: []
      - all_parents_must_converge: false
        identifier: tpl_leapp_analysis
        unified_job_template: tpl_leapp_analysis
        credentials: []
        success_nodes:
          - tpl_leapp_ipu
        failure_nodes: []
        always_nodes: []
      - all_parents_must_converge: false
        identifier: tpl_leapp_ipu
        unified_job_template: tpl_leapp_ipu
        credentials: []
        success_nodes: []
        failure_nodes: []
        always_nodes: []
    notification_templates_started: []
    notification_templates_success: []
    notification_templates_error: []
    notification_templates_approvals: []
    survey_spec:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: upgrade_group
          choices:
            - grp_satellite_upgrade
          required: true
        - question_name: Set size of /boot partition
          type: text
          variable: partition_size
          default: "200M"
          required: true
        - question_name: Skip upgrade to latest RHEL 7.9
          type: multiplechoice
          variable: skip_latest_rhel7
          choices:
            - "yes"
            - "no"
          required: false
  - name: wflow_ipu_rhel8
    description: In-place upgrade from RHEL 8 to RHEL 9
    extra_vars: ''
    survey_enabled: true
    allow_simultaneous: false
    ask_variables_on_launch: false
    inventory: inv_satellite_production
    limit: client2.london.example.com
    scm_branch:
    ask_inventory_on_launch: true
    ask_scm_branch_on_launch: false
    ask_limit_on_launch: true
    webhook_service: ''
    webhook_credential:
    organization: Default
    schedules: []
    simplified_workflow_nodes:
      - all_parents_must_converge: false
        identifier: tpl_leapp_remediate
        unified_job_template: tpl_leapp_remediate
        credentials: []
        success_nodes:
          - tpl_leapp_bigboot
        failure_nodes: []
        always_nodes: []
      - all_parents_must_converge: false
        identifier: tpl_leapp_bigboot
        unified_job_template: tpl_leapp_bigboot
        credentials: []
        success_nodes:
          - tpl_leapp_analysis
        failure_nodes: []
        always_nodes: []
      - all_parents_must_converge: false
        identifier: tpl_leapp_analysis
        unified_job_template: tpl_leapp_analysis
        credentials: []
        success_nodes:
          - tpl_leapp_ipu
        failure_nodes: []
        always_nodes: []
      - all_parents_must_converge: false
        identifier: tpl_leapp_ipu
        unified_job_template: tpl_leapp_ipu
        credentials: []
        success_nodes: []
        failure_nodes: []
        always_nodes: []
    notification_templates_started: []
    notification_templates_success: []
    notification_templates_error: []
    notification_templates_approvals: []
    survey_spec:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: upgrade_group
          choices:
            - grp_satellite_upgrade
          required: true
        - question_name: Set size of /boot partition
          type: text
          variable: partition_size
          default: "200M"
          required: true
  - name: wflow_ipu_rhel7_to_rhel9
    description: In-place upgrade from RHEL 7 to RHEL 9
    extra_vars: ''
    survey_enabled: true
    allow_simultaneous: false
    ask_variables_on_launch: false
    inventory: inv_satellite_production
    limit: client2.london.example.com
    scm_branch:
    ask_inventory_on_launch: true
    ask_scm_branch_on_launch: false
    ask_limit_on_launch: true
    webhook_service: ''
    webhook_credential:
    organization: Default
    schedules: []
    simplified_workflow_nodes:
      - all_parents_must_converge: false
        identifier: wflow_ipu_rhel7
        unified_job_template: wflow_ipu_rhel7
        credentials: []
        success_nodes:
          - wflow_ipu_rhel8
        failure_nodes: []
        always_nodes: []
      - all_parents_must_converge: false
        identifier: wflow_ipu_rhel8
        unified_job_template: wflow_ipu_rhel8
        credentials: []
        failure_nodes: []
        always_nodes: []
    notification_templates_started: []
    notification_templates_success: []
    notification_templates_error: []
    notification_templates_approvals: []
    survey_spec:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: upgrade_group
          choices:
            - grp_satellite_upgrade
          required: true
        - question_name: Set size of /boot partition
          type: text
          variable: partition_size
          default: "200M"
          required: true
        - question_name: Skip upgrade to latest RHEL 7.9
          type: multiplechoice
          variable: skip_latest_rhel7
          choices:
            - "yes"
            - "no"
          required: false
        - question_name: Target RHEL Major release
          type: multiplechoice
          variable: ipu_target
          choices:
            - "7"
            - "8"
            - "9"
          required: false
...
