---
controller_inventory_sources:
  - name: inv_src_satellite_production
    organization: "{{ ansible_organization_name }}"
    source: satellite6
    inventory: inv_satellite_production
    credential: cred_sat6_admin
    overwrite: true
    overwrite_vars: true
    update_cache_timeout: 0
    # https://access.redhat.com/solutions/6995422
    source_vars:
      validate_certs: false
...
